version: '3.6'

services:
  consul:
    image: consul
    environment:
      CONSUL_BIND_INTERFACE: "eth0"
      CONSUL_LOCAL_CONFIG: '{"skip_leave_on_interrupt": true}'
    deploy:
      replicas: 1
      update_config:
        parallelism: 1
        delay: 10s
      restart_policy:
        condition: on-failure
    command: agent -server -ui -client=0.0.0.0 -bootstrap-expect=1 -retry-join=consul
    networks:
      - skynet

networks:
  skynet:
    driver: overlay