version: '3.6'

services:
  rabbitmq_cluster_channels_daphne:
    image: eavictor/rabbitmq_autocluster:3.6.15-management
    environment:
      AUTOCLUSTER_TYPE: "consul"
      CONSUL_HOST: "consul"
      CONSUL_PORT: "8500"
      CONSUL_SVC: "rabbitmq"
      CONSUL_SVC_ADDR_AUTO: "true"
      AUTOCLUSTER_CLEANUP: "true"
      CLEANUP_WARN_ONLY: "false"
      RABBITMQ_ERLANG_COOKIE: "daphne"
      RABBITMQ_DEFAULT_USER: "eavictor"
      RABBITMQ_DEFAULT_PASS: "acgnotamashi"
    ports:
      - "5672"
      - "15672:15672"
    depends_on:
     - consul
    networks:
      - skynet
    deploy:
      mode: global
      update_config:
        parallelism: 1
        delay: 10s
      restart_policy:
        condition: on-failure

  rabbitmq_cluster_channels_worker:
    image: eavictor/rabbitmq_autocluster:3.6.15-management
    environment:
      AUTOCLUSTER_TYPE: "consul"
      CONSUL_HOST: "consul"
      CONSUL_PORT: "8500"
      CONSUL_SVC: "rabbitmq"
      CONSUL_SVC_ADDR_AUTO: "true"
      AUTOCLUSTER_CLEANUP: "true"
      CLEANUP_WARN_ONLY: "false"
      RABBITMQ_ERLANG_COOKIE: "worker"
      RABBITMQ_DEFAULT_USER: "eavictor"
      RABBITMQ_DEFAULT_PASS: "acgnotamashi"
    ports:
      - "5672"
      - "15673:15672"
    depends_on:
     - consul
    networks:
      - skynet
    deploy:
      mode: global
      update_config:
        parallelism: 1
        delay: 10s
      restart_policy:
        condition: on-failure

  rabbitmq_cluster_external:
    image: eavictor/rabbitmq_autocluster:3.6.15-management
    environment:
      AUTOCLUSTER_TYPE: "consul"
      CONSUL_HOST: "consul"
      CONSUL_PORT: "8500"
      CONSUL_SVC: "rabbitmq"
      CONSUL_SVC_ADDR_AUTO: "true"
      AUTOCLUSTER_CLEANUP: "true"
      CLEANUP_WARN_ONLY: "false"
      RABBITMQ_ERLANG_COOKIE: "image"
      RABBITMQ_DEFAULT_USER: "eavictor"
      RABBITMQ_DEFAULT_PASS: "acgnotamashi"
    ports:
      - "5672"
      - "15674:15672"
    depends_on:
     - consul
    networks:
      - skynet
    deploy:
      mode: global
      update_config:
        parallelism: 1
        delay: 10s
      restart_policy:
        condition: on-failure

networks:
  skynet:
    driver: overlay