version: '3.6'

services:
  daphne:
    image: eavictor/website:1.3
    ports:
     - "80:80"
     - "8000:8000"
    deploy:
      mode: global
      update_config:
        parallelism: 1
        delay: 10s
      restart_policy:
        condition: on-failure
    depends_on:
     - rabbitmq_cluster_channels_daphne
     - rabbitmq_cluster_channels_worker
     - rabbitmq_cluster_external
    networks:
     - skynet
    command: ./daphne.sh

  worker:
    image: eavictor/website:1.3
    deploy:
      replicas: 3
      update_config:
        parallelism: 1
        delay: 10s
      restart_policy:
        condition: on-failure
    depends_on:
     - daphne
     - rabbitmq_cluster_channels_daphne
     - rabbitmq_cluster_channels_worker
     - rabbitmq_cluster_external
    command: ./runworker.sh
    networks:
     - skynet

  image_recognition:
    image: eavictor/image_recognition:1.3
    deploy:
      replicas: 3
      update_config:
        parallelism: 1
        delay: 10s
      restart_policy:
        condition: on-failure
    depends_on:
     - rabbitmq_cluster_external

networks:
  skynet:
    driver: overlay
