version: '3.3'

services:
#  nginx:
#    image: eavictor/nginx
#    ports:
#     - '80:80'
#    deploy:
#      mode: global
#      update_config:
#        parallelism: 1
#        delay: 10s
#      restart_policy:
#        condition: on-failure
#        delay: 10s
#    depends_on:
#     - web
#     - worker
#    networks:
#     - skynet


  web:
    image: eavictor/web
    ports:
     - "80:80"
    deploy:
      mode: global
      update_config:
        parallelism: 1
        delay: 10s
      restart_policy:
        condition: on-failure
    depends_on:
     - db
     - rabbitmq
    networks:
     - skynet
    command: ./daphne.sh


  worker:
    image: eavictor/web
    deploy:
      mode: global
      update_config:
        parallelism: 1
        delay: 10s
      restart_policy:
        condition: on-failure
    depends_on:
     - web
     - db
     - rabbitmq
    command: ./runworker.sh
    networks:
     - skynet


  db:
    image: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: "P@ssw0rd"
      MYSQL_DATABASE: "main"
      MYSQL_USER: "eavictor"
      MYSQL_PASSWORD: "acgnotamashi"
    ports:
     - "3306:3306"
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    deploy:
      replicas: 1
      restart_policy:
        condition: never
    networks:
     - skynet

  consul:
    image: consul
    environment:
      CONSUL_BIND_INTERFACE: "eth0"
      CONSUL_LOCAL_CONFIG: '{"skip_leave_on_interrupt": true}'
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    command: agent -server -ui -client=0.0.0.0 -bootstrap-expect=1 -retry-join=consul
    networks:
      - skynet


  rabbitmq:
    image: eavictor/rabbitmq
    environment:
      AUTOCLUSTER_TYPE: "consul"
      CONSUL_HOST: "consul"
      CONSUL_PORT: "8500"
      CONSUL_SVC: "rabbitmq"
      CONSUL_SVC_ADDR_AUTO: "true"
      AUTOCLUSTER_CLEANUP: "true"
      CLEANUP_WARN_ONLY: "false"
      RABBITMQ_ERLANG_COOKIE: "secrect"
      RABBITMQ_DEFAULT_USER: "eavictor"
      RABBITMQ_DEFAULT_PASS: "acgnotamashi"
    ports:
      - "5672:5672"
      - "15672:15672"
    depends_on:
     - consul
    networks:
      - skynet
    deploy:
      mode: global
      restart_policy:
        condition: on-failure


networks:
  skynet:
    driver: overlay