version: '3.6'

services:
  consul:
    image: consul
    environment:
      CONSUL_BIND_INTERFACE: "eth0"
      CONSUL_LOCAL_CONFIG: '{"skip_leave_on_interrupt": true}'
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    command: agent -server -ui -client=0.0.0.0 -bootstrap-expect=1 -retry-join=consul
    networks:
      - skynet

  rabbitmq_cluster_channels_daphne:
    image: eavictor/rabbitmq_autocluster:1.3
      environment:
        AUTOCLUSTER_TYPE: "consul"
        CONSUL_HOST: "consul"
        CONSUL_PORT: "8500"
        CONSUL_SVC: "rabbitmq"
        CONSUL_SVC_ADDR_AUTO: "true"
        AUTOCLUSTER_CLEANUP: "true"
        CLEANUP_WARN_ONLY: "false"
        RABBITMQ_ERLANG_COOKIE: "daphne"
        RABBITMQ_DEFAULT_USER: "eavictor"
        RABBITMQ_DEFAULT_PASS: "acgnotamashi"
    ports:
      - "5672:5672"
      - "15672:15672"
    depends_on:
     - consul
    networks:
      - skynet
    deploy:
      mode: global
      restart_policy:
        condition: on-failure

  rabbitmq_cluster_channels_worker:
    image: eavictor/rabbitmq_autocluster:1.3
    environment:
      AUTOCLUSTER_TYPE: "consul"
      CONSUL_HOST: "consul"
      CONSUL_PORT: "8500"
      CONSUL_SVC: "rabbitmq"
      CONSUL_SVC_ADDR_AUTO: "true"
      AUTOCLUSTER_CLEANUP: "true"
      CLEANUP_WARN_ONLY: "false"
      RABBITMQ_ERLANG_COOKIE: "worker"
      RABBITMQ_DEFAULT_USER: "eavictor"
      RABBITMQ_DEFAULT_PASS: "acgnotamashi"
    ports:
      - "5673:5672"
      - "15673:15672"
    depends_on:
     - consul
    networks:
      - skynet
    deploy:
      mode: global
      restart_policy:
        condition: on-failure

  rabbitmq_cluster_external:
    image: eavictor/rabbitmq_autocluster:1.3
    environment:
      AUTOCLUSTER_TYPE: "consul"
      CONSUL_HOST: "consul"
      CONSUL_PORT: "8500"
      CONSUL_SVC: "rabbitmq"
      CONSUL_SVC_ADDR_AUTO: "true"
      AUTOCLUSTER_CLEANUP: "true"
      CLEANUP_WARN_ONLY: "false"
      RABBITMQ_ERLANG_COOKIE: "image"
      RABBITMQ_DEFAULT_USER: "eavictor"
      RABBITMQ_DEFAULT_PASS: "acgnotamashi"
    ports:
      - "5674:5672"
      - "15674:15672"
    depends_on:
     - consul
    networks:
      - skynet
    deploy:
      mode: global
      restart_policy:
        condition: on-failure

  daphne:
    image: eavictor/website:1.3
    ports:
     - "80:80"
    deploy:
      mode: global
      update_config:
        parallelism: 1
        delay: 10s
      restart_policy:
        condition: on-failure
    depends_on:
     - rabbitmq_cluster_channels_daphne
     - rabbitmq_cluster_channels_worker
     - rabbitmq_cluster_external
    networks:
     - skynet
    command: ./daphne.sh

  worker:
    image: eavictor/website:1.3
    deploy:
      replicas: 12
      update_config:
        parallelism: 1
        delay: 10s
      restart_policy:
        condition: on-failure
    depends_on:
     - daphne
     - rabbitmq_cluster_channels_daphne
     - rabbitmq_cluster_channels_worker
     - rabbitmq_cluster_external
    command: ./runworker.sh
    networks:
     - skynet

  image_recognition:
    image: eavictor/image_recognition:1.3
    deploy:
      replicas: 3
      update_config:
        parallelism: 1
        delay: 10s
      restart_policy:
        condition: on-failure
    depends_on:
     - rabbitmq_cluster_external

networks:
  skynet:
    driver: overlay
